### ISSUE TITLE
Unable to create env in conda in codespaces

### ISSUE THREAD

**Issue by prakharguptaujjain** [stratosphereips/AIP#7]
$conda env create -f environment.yml
Collecting package metadata (repodata.json): \ Killed

Can somebody help

**Comment by prakharguptaujjain** [comment]
I did this on a newly created codespaces repo forked from https://github.com/stratosphereips/AIP

**Comment by prakharguptaujjain** [comment]
Ya, I am sorry , docker was working, but not directly conda

**Comment by verovaleros** [comment]
Is conda required only for the docker? If yes, then we can close the issue. If not, @jwackito can you give some technical specs on how a solution would look like so others can help?

**Comment by verovaleros** [comment]
Hello @prakharguptaujjain, 

Thanks for your patience. I have just tried to reproduce the issues. We have updated the Conda environment so that probably helped solve this.

This worked:
1. Create a new fork or sync the existing fork with the current main AIP
2. Create a new codespace from fork
3. Open a terminal
4. The `conda --version` shows conda is installed in version 23.1.0: ![image](https://github.com/stratosphereips/AIP/assets/2458879/3988b180-4895-4462-a36a-3280c8fc602b)
5. Init conda `conda init`
6. Close terminal and reopen a new terminal
7. Create the conda environment with `conda env create -f environment.yml`:  ![image](https://github.com/stratosphereips/AIP/assets/2458879/e50dc9b5-f33f-494f-b608-5c1c15dc9481)
8. Wait for packages to install: ![image](https://github.com/stratosphereips/AIP/assets/2458879/850d8c5e-6fde-4398-b3b8-2d2df2ffb098)
9. Then activate environment `conda activate aip`:  ![image](https://github.com/stratosphereips/AIP/assets/2458879/6093b7bc-831a-4f30-876f-1db599b6bf52)


This should solve the problem. If you are still encountering issues, please re-open this issue and we will take a look again. Thanks for your interest in AIP!
